name: Changelog CI

on:
  pull_request:
    types: [opened]

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Asegura permisos de escritura

    steps:
      - uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Obtener versión para Changelog
        id: version_step
        run: |
          if [ -z "${{ github.event.inputs.release_version }}" ]; then
            VERSION=$(cat version.txt)
          else
            VERSION="${{ github.event.inputs.release_version }}"
          fi
          VERSION_CLEAN=$(echo "$VERSION" | tr -cd '[:alnum:]._-')
          echo "release_version=$VERSION_CLEAN" >> $GITHUB_OUTPUT

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .changelog-config.yml
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          release_version: ${{ steps.version_step.outputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR automáticamente
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.GITHUB_REF.split('/')[2];
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });
