name: Changelog CI

on:
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Version for Changelog
        id: version_step
        run: |
          if [ -z "${{ github.event.inputs.release_version }}" ]; then
            echo "release_version=$(cat version.txt)" >> $GITHUB_OUTPUT
          else
            echo "release_version=${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .changelog-config.yml
          committer_username: 'github-actions[bot]'
          committer_email: '41898282+github-actions[bot]@users.noreply.github.com'
          release_version: ${{ steps.version_step.outputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge automático para conflictos
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git fetch origin main
          git checkout main
          git merge --strategy-option theirs changelog-ci-${{ steps.version_step.outputs.release_version }} || git merge --abort
          git add CHANGELOG.md
          git commit -m "fix: Resuelto conflicto en CHANGELOG.md" || echo "Sin cambios para commitear"
          git push origin main
