name: Changelog CI  #prueba

on:
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      release_version:
        description: "Set Release Version"
        required: true

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Get Version for Changelog
        id: version_step
        run: |
          if [ -z "${{ github.event.inputs.release_version }}" ]; then
          version=$(cat version.txt)
          else
          version="${{ github.event.inputs.release_version }}"
          fi

          # Limpiamos caracteres no válidos en la versión
          version_clean=$(echo "$version" | tr -d '[:space:]' | tr -cd '[:alnum:]._-')

          echo "release_version=$version_clean" >> $GITHUB_OUTPUT

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .changelog-config.yml
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          release_version: ${{ steps.version_step.outputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge automático para conflictos
        run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
         # Listamos las ramas remotas para depuración
         git ls-remote --heads origin
        
         # Asegúrate de usar el nombre correcto de la rama creada por la acción
         MERGE_BRANCH="changelog-ci-${{ steps.version_step.outputs.release_version }}"
         echo "Intentando merge de la rama $MERGE_BRANCH a main"
        
         git fetch origin main
         git checkout main
         git merge --strategy-option theirs $MERGE_BRANCH || git merge --abort
            git add CHANGELOG.md
         git commit -m "fix: Resuelto conflicto en CHANGELOG.md" || echo "Sin cambios para commitear"
         git push origin main
        
