name: Update Version in dev

on:
  push:
    branches:
      - dev

jobs:
  update-version-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get current version
        id: current_version
        run: |
          echo "current_version=$(cat version.txt)" >> $GITHUB_OUTPUT
          echo "La versión actual es: $(cat version.txt)"

      - name: Bump version
        id: bump
        run: |
          # Ajusta la lógica según cómo desees incrementar la versión.
          # Por ejemplo, incrementamos el número menor:
          NEW_VERSION=$(echo "${{ steps.current_version.outputs.current_version }}" | awk -F. '{ $2 += 1; $3 = 0; print }' OFS=".")
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > version.txt
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}" || echo "No changes to commit"
          git push origin dev
